// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { ItemType } from '../../nexiq/graph-view/item-type.js';


export class GraphCombo {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):GraphCombo {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsGraphCombo(bb:flatbuffers.ByteBuffer, obj?:GraphCombo):GraphCombo {
  return (obj || new GraphCombo()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsGraphCombo(bb:flatbuffers.ByteBuffer, obj?:GraphCombo):GraphCombo {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new GraphCombo()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

id():string|null
id(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
id(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

type():ItemType {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : ItemType.Package;
}

name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

displayName():string|null
displayName(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
displayName(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

parentId():string|null
parentId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
parentId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

color():string|null
color(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
color(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

radius():number {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

collapsed():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

gitStatus():string|null
gitStatus(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
gitStatus(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startGraphCombo(builder:flatbuffers.Builder) {
  builder.startObject(9);
}

static addId(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, idOffset, 0);
}

static addType(builder:flatbuffers.Builder, type:ItemType) {
  builder.addFieldInt8(1, type, ItemType.Package);
}

static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, nameOffset, 0);
}

static addDisplayName(builder:flatbuffers.Builder, displayNameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, displayNameOffset, 0);
}

static addParentId(builder:flatbuffers.Builder, parentIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, parentIdOffset, 0);
}

static addColor(builder:flatbuffers.Builder, colorOffset:flatbuffers.Offset) {
  builder.addFieldOffset(5, colorOffset, 0);
}

static addRadius(builder:flatbuffers.Builder, radius:number) {
  builder.addFieldFloat32(6, radius, 0.0);
}

static addCollapsed(builder:flatbuffers.Builder, collapsed:boolean) {
  builder.addFieldInt8(7, +collapsed, +false);
}

static addGitStatus(builder:flatbuffers.Builder, gitStatusOffset:flatbuffers.Offset) {
  builder.addFieldOffset(8, gitStatusOffset, 0);
}

static endGraphCombo(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createGraphCombo(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset, type:ItemType, nameOffset:flatbuffers.Offset, displayNameOffset:flatbuffers.Offset, parentIdOffset:flatbuffers.Offset, colorOffset:flatbuffers.Offset, radius:number, collapsed:boolean, gitStatusOffset:flatbuffers.Offset):flatbuffers.Offset {
  GraphCombo.startGraphCombo(builder);
  GraphCombo.addId(builder, idOffset);
  GraphCombo.addType(builder, type);
  GraphCombo.addName(builder, nameOffset);
  GraphCombo.addDisplayName(builder, displayNameOffset);
  GraphCombo.addParentId(builder, parentIdOffset);
  GraphCombo.addColor(builder, colorOffset);
  GraphCombo.addRadius(builder, radius);
  GraphCombo.addCollapsed(builder, collapsed);
  GraphCombo.addGitStatus(builder, gitStatusOffset);
  return GraphCombo.endGraphCombo(builder);
}
}
