// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { GraphCombo } from '../../nexiq/graph-view/graph-combo.js';
import { GraphEdge } from '../../nexiq/graph-view/graph-edge.js';
import { GraphNode } from '../../nexiq/graph-view/graph-node.js';
import { GraphNodeDetail } from '../../nexiq/graph-view/graph-node-detail.js';


export class GraphView {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):GraphView {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsGraphView(bb:flatbuffers.ByteBuffer, obj?:GraphView):GraphView {
  return (obj || new GraphView()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsGraphView(bb:flatbuffers.ByteBuffer, obj?:GraphView):GraphView {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new GraphView()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static bufferHasIdentifier(bb:flatbuffers.ByteBuffer):boolean {
  return bb.__has_identifier('NXGV');
}

nodes(index: number, obj?:GraphNode):GraphNode|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new GraphNode()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

nodesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

combos(index: number, obj?:GraphCombo):GraphCombo|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new GraphCombo()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

combosLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

edges(index: number, obj?:GraphEdge):GraphEdge|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new GraphEdge()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

edgesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

details(index: number, obj?:GraphNodeDetail):GraphNodeDetail|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? (obj || new GraphNodeDetail()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

detailsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startGraphView(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addNodes(builder:flatbuffers.Builder, nodesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, nodesOffset, 0);
}

static createNodesVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startNodesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addCombos(builder:flatbuffers.Builder, combosOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, combosOffset, 0);
}

static createCombosVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startCombosVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addEdges(builder:flatbuffers.Builder, edgesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, edgesOffset, 0);
}

static createEdgesVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startEdgesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addDetails(builder:flatbuffers.Builder, detailsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, detailsOffset, 0);
}

static createDetailsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startDetailsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endGraphView(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static finishGraphViewBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, 'NXGV');
}

static finishSizePrefixedGraphViewBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, 'NXGV', true);
}

static createGraphView(builder:flatbuffers.Builder, nodesOffset:flatbuffers.Offset, combosOffset:flatbuffers.Offset, edgesOffset:flatbuffers.Offset, detailsOffset:flatbuffers.Offset):flatbuffers.Offset {
  GraphView.startGraphView(builder);
  GraphView.addNodes(builder, nodesOffset);
  GraphView.addCombos(builder, combosOffset);
  GraphView.addEdges(builder, edgesOffset);
  GraphView.addDetails(builder, detailsOffset);
  return GraphView.endGraphView(builder);
}
}
