// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { Loc } from '../../nexiq/graph-view/loc.js';


export class GraphNodeDetail {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):GraphNodeDetail {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsGraphNodeDetail(bb:flatbuffers.ByteBuffer, obj?:GraphNodeDetail):GraphNodeDetail {
  return (obj || new GraphNodeDetail()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsGraphNodeDetail(bb:flatbuffers.ByteBuffer, obj?:GraphNodeDetail):GraphNodeDetail {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new GraphNodeDetail()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

id():string|null
id(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
id(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

fileName():string|null
fileName(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
fileName(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

projectPath():string|null
projectPath(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
projectPath(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

loc(obj?:Loc):Loc|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? (obj || new Loc()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

dataJson():string|null
dataJson(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
dataJson(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startGraphNodeDetail(builder:flatbuffers.Builder) {
  builder.startObject(5);
}

static addId(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, idOffset, 0);
}

static addFileName(builder:flatbuffers.Builder, fileNameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, fileNameOffset, 0);
}

static addProjectPath(builder:flatbuffers.Builder, projectPathOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, projectPathOffset, 0);
}

static addLoc(builder:flatbuffers.Builder, locOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, locOffset, 0);
}

static addDataJson(builder:flatbuffers.Builder, dataJsonOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, dataJsonOffset, 0);
}

static endGraphNodeDetail(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
