// automatically generated by the FlatBuffers compiler, do not modify

export enum ItemType {
  Package = 0,
  Scope = 1,
  Component = 2,
  Hook = 3,
  State = 4,
  Memo = 5,
  Callback = 6,
  Ref = 7,
  Effect = 8,
  Prop = 9,
  Render = 10,
  RenderGroup = 11,
  SourceGroup = 12,
  PathGroup = 13,
  Variable = 14
}
