// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class Loc {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Loc {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsLoc(bb:flatbuffers.ByteBuffer, obj?:Loc):Loc {
  return (obj || new Loc()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsLoc(bb:flatbuffers.ByteBuffer, obj?:Loc):Loc {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Loc()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

line():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

column():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

static startLoc(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addLine(builder:flatbuffers.Builder, line:number) {
  builder.addFieldInt32(0, line, 0);
}

static addColumn(builder:flatbuffers.Builder, column:number) {
  builder.addFieldInt32(1, column, 0);
}

static endLoc(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createLoc(builder:flatbuffers.Builder, line:number, column:number):flatbuffers.Offset {
  Loc.startLoc(builder);
  Loc.addLine(builder, line);
  Loc.addColumn(builder, column);
  return Loc.endLoc(builder);
}
}
