packages:
  - packages/*
  - packages/sample-project/*
  - benchmarks/viewer
  - benchmarks/cli

ignoredBuiltDependencies:
  - "@swc/core"

strictPeerDependencies: false

nodeLinker: isolated

# hoist: false
# hoistPattern:
#   - "!better-sqlite3"
#   - "!**/better-sqlite3"
#   - "!**/better-sqlite3/**"
