/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface TaskContext {
  projectRoot: string
  viewType: string
  cacheDbPath?: string
}
export declare function runComponentTaskSqlite(context: TaskContext): Buffer
