/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface TaskContext {
  projectRoot: string
  sqlitePath: string
  viewType: string
}
export declare function runComponentTask(nodeDataBuffer: Buffer, detailBuffer: Buffer, context: TaskContext): number
