// automatically generated by the FlatBuffers compiler, do not modify


// @generated

use core::mem;
use core::cmp::Ordering;

extern crate flatbuffers;
use self::flatbuffers::{EndianScalar, Follow};

#[allow(unused_imports, dead_code)]
pub mod nexiq {

  use core::mem;
  use core::cmp::Ordering;

  extern crate flatbuffers;
  use self::flatbuffers::{EndianScalar, Follow};
#[allow(unused_imports, dead_code)]
pub mod graph_view {

  use core::mem;
  use core::cmp::Ordering;

  extern crate flatbuffers;
  use self::flatbuffers::{EndianScalar, Follow};

#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_ITEM_TYPE: i8 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_ITEM_TYPE: i8 = 14;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_ITEM_TYPE: [ItemType; 15] = [
  ItemType::Package,
  ItemType::Scope,
  ItemType::Component,
  ItemType::Hook,
  ItemType::State,
  ItemType::Memo,
  ItemType::Callback,
  ItemType::Ref,
  ItemType::Effect,
  ItemType::Prop,
  ItemType::Render,
  ItemType::RenderGroup,
  ItemType::SourceGroup,
  ItemType::PathGroup,
  ItemType::Variable,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct ItemType(pub i8);
#[allow(non_upper_case_globals)]
impl ItemType {
  pub const Package: Self = Self(0);
  pub const Scope: Self = Self(1);
  pub const Component: Self = Self(2);
  pub const Hook: Self = Self(3);
  pub const State: Self = Self(4);
  pub const Memo: Self = Self(5);
  pub const Callback: Self = Self(6);
  pub const Ref: Self = Self(7);
  pub const Effect: Self = Self(8);
  pub const Prop: Self = Self(9);
  pub const Render: Self = Self(10);
  pub const RenderGroup: Self = Self(11);
  pub const SourceGroup: Self = Self(12);
  pub const PathGroup: Self = Self(13);
  pub const Variable: Self = Self(14);

  pub const ENUM_MIN: i8 = 0;
  pub const ENUM_MAX: i8 = 14;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::Package,
    Self::Scope,
    Self::Component,
    Self::Hook,
    Self::State,
    Self::Memo,
    Self::Callback,
    Self::Ref,
    Self::Effect,
    Self::Prop,
    Self::Render,
    Self::RenderGroup,
    Self::SourceGroup,
    Self::PathGroup,
    Self::Variable,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::Package => Some("Package"),
      Self::Scope => Some("Scope"),
      Self::Component => Some("Component"),
      Self::Hook => Some("Hook"),
      Self::State => Some("State"),
      Self::Memo => Some("Memo"),
      Self::Callback => Some("Callback"),
      Self::Ref => Some("Ref"),
      Self::Effect => Some("Effect"),
      Self::Prop => Some("Prop"),
      Self::Render => Some("Render"),
      Self::RenderGroup => Some("RenderGroup"),
      Self::SourceGroup => Some("SourceGroup"),
      Self::PathGroup => Some("PathGroup"),
      Self::Variable => Some("Variable"),
      _ => None,
    }
  }
}
impl core::fmt::Debug for ItemType {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> flatbuffers::Follow<'a> for ItemType {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = flatbuffers::read_scalar_at::<i8>(buf, loc);
    Self(b)
  }
}

impl flatbuffers::Push for ItemType {
    type Output = ItemType;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        flatbuffers::emplace_scalar::<i8>(dst, self.0);
    }
}

impl flatbuffers::EndianScalar for ItemType {
  type Scalar = i8;
  #[inline]
  fn to_little_endian(self) -> i8 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: i8) -> Self {
    let b = i8::from_le(v);
    Self(b)
  }
}

impl<'a> flatbuffers::Verifiable for ItemType {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    i8::run_verifier(v, pos)
  }
}

impl flatbuffers::SimpleToVerifyInSlice for ItemType {}
pub enum LocOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Loc<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for Loc<'a> {
  type Inner = Loc<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> Loc<'a> {
  pub const VT_LINE: flatbuffers::VOffsetT = 4;
  pub const VT_COLUMN: flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    Loc { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args LocArgs
  ) -> flatbuffers::WIPOffset<Loc<'bldr>> {
    let mut builder = LocBuilder::new(_fbb);
    builder.add_column(args.column);
    builder.add_line(args.line);
    builder.finish()
  }


  #[inline]
  pub fn line(&self) -> i32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i32>(Loc::VT_LINE, Some(0)).unwrap()}
  }
  #[inline]
  pub fn column(&self) -> i32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i32>(Loc::VT_COLUMN, Some(0)).unwrap()}
  }
}

impl flatbuffers::Verifiable for Loc<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<i32>("line", Self::VT_LINE, false)?
     .visit_field::<i32>("column", Self::VT_COLUMN, false)?
     .finish();
    Ok(())
  }
}
pub struct LocArgs {
    pub line: i32,
    pub column: i32,
}
impl<'a> Default for LocArgs {
  #[inline]
  fn default() -> Self {
    LocArgs {
      line: 0,
      column: 0,
    }
  }
}

pub struct LocBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> LocBuilder<'a, 'b> {
  #[inline]
  pub fn add_line(&mut self, line: i32) {
    self.fbb_.push_slot::<i32>(Loc::VT_LINE, line, 0);
  }
  #[inline]
  pub fn add_column(&mut self, column: i32) {
    self.fbb_.push_slot::<i32>(Loc::VT_COLUMN, column, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> LocBuilder<'a, 'b> {
    let start = _fbb.start_table();
    LocBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<Loc<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for Loc<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("Loc");
      ds.field("line", &self.line());
      ds.field("column", &self.column());
      ds.finish()
  }
}
pub enum GraphNodeOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct GraphNode<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for GraphNode<'a> {
  type Inner = GraphNode<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> GraphNode<'a> {
  pub const VT_ID: flatbuffers::VOffsetT = 4;
  pub const VT_TYPE_: flatbuffers::VOffsetT = 6;
  pub const VT_NAME: flatbuffers::VOffsetT = 8;
  pub const VT_DISPLAYNAME: flatbuffers::VOffsetT = 10;
  pub const VT_COMBOID: flatbuffers::VOffsetT = 12;
  pub const VT_COLOR: flatbuffers::VOffsetT = 14;
  pub const VT_RADIUS: flatbuffers::VOffsetT = 16;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    GraphNode { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args GraphNodeArgs<'args>
  ) -> flatbuffers::WIPOffset<GraphNode<'bldr>> {
    let mut builder = GraphNodeBuilder::new(_fbb);
    builder.add_radius(args.radius);
    if let Some(x) = args.color { builder.add_color(x); }
    if let Some(x) = args.comboId { builder.add_comboId(x); }
    if let Some(x) = args.displayName { builder.add_displayName(x); }
    if let Some(x) = args.name { builder.add_name(x); }
    if let Some(x) = args.id { builder.add_id(x); }
    builder.add_type_(args.type_);
    builder.finish()
  }


  #[inline]
  pub fn id(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(GraphNode::VT_ID, None)}
  }
  #[inline]
  pub fn type_(&self) -> ItemType {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<ItemType>(GraphNode::VT_TYPE_, Some(ItemType::Package)).unwrap()}
  }
  #[inline]
  pub fn name(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(GraphNode::VT_NAME, None)}
  }
  #[inline]
  pub fn displayName(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(GraphNode::VT_DISPLAYNAME, None)}
  }
  #[inline]
  pub fn comboId(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(GraphNode::VT_COMBOID, None)}
  }
  #[inline]
  pub fn color(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(GraphNode::VT_COLOR, None)}
  }
  #[inline]
  pub fn radius(&self) -> f32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f32>(GraphNode::VT_RADIUS, Some(0.0)).unwrap()}
  }
}

impl flatbuffers::Verifiable for GraphNode<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("id", Self::VT_ID, false)?
     .visit_field::<ItemType>("type_", Self::VT_TYPE_, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("name", Self::VT_NAME, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("displayName", Self::VT_DISPLAYNAME, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("comboId", Self::VT_COMBOID, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("color", Self::VT_COLOR, false)?
     .visit_field::<f32>("radius", Self::VT_RADIUS, false)?
     .finish();
    Ok(())
  }
}
pub struct GraphNodeArgs<'a> {
    pub id: Option<flatbuffers::WIPOffset<&'a str>>,
    pub type_: ItemType,
    pub name: Option<flatbuffers::WIPOffset<&'a str>>,
    pub displayName: Option<flatbuffers::WIPOffset<&'a str>>,
    pub comboId: Option<flatbuffers::WIPOffset<&'a str>>,
    pub color: Option<flatbuffers::WIPOffset<&'a str>>,
    pub radius: f32,
}
impl<'a> Default for GraphNodeArgs<'a> {
  #[inline]
  fn default() -> Self {
    GraphNodeArgs {
      id: None,
      type_: ItemType::Package,
      name: None,
      displayName: None,
      comboId: None,
      color: None,
      radius: 0.0,
    }
  }
}

pub struct GraphNodeBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> GraphNodeBuilder<'a, 'b> {
  #[inline]
  pub fn add_id(&mut self, id: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(GraphNode::VT_ID, id);
  }
  #[inline]
  pub fn add_type_(&mut self, type_: ItemType) {
    self.fbb_.push_slot::<ItemType>(GraphNode::VT_TYPE_, type_, ItemType::Package);
  }
  #[inline]
  pub fn add_name(&mut self, name: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(GraphNode::VT_NAME, name);
  }
  #[inline]
  pub fn add_displayName(&mut self, displayName: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(GraphNode::VT_DISPLAYNAME, displayName);
  }
  #[inline]
  pub fn add_comboId(&mut self, comboId: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(GraphNode::VT_COMBOID, comboId);
  }
  #[inline]
  pub fn add_color(&mut self, color: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(GraphNode::VT_COLOR, color);
  }
  #[inline]
  pub fn add_radius(&mut self, radius: f32) {
    self.fbb_.push_slot::<f32>(GraphNode::VT_RADIUS, radius, 0.0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> GraphNodeBuilder<'a, 'b> {
    let start = _fbb.start_table();
    GraphNodeBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<GraphNode<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for GraphNode<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("GraphNode");
      ds.field("id", &self.id());
      ds.field("type_", &self.type_());
      ds.field("name", &self.name());
      ds.field("displayName", &self.displayName());
      ds.field("comboId", &self.comboId());
      ds.field("color", &self.color());
      ds.field("radius", &self.radius());
      ds.finish()
  }
}
pub enum GraphComboOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct GraphCombo<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for GraphCombo<'a> {
  type Inner = GraphCombo<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> GraphCombo<'a> {
  pub const VT_ID: flatbuffers::VOffsetT = 4;
  pub const VT_TYPE_: flatbuffers::VOffsetT = 6;
  pub const VT_NAME: flatbuffers::VOffsetT = 8;
  pub const VT_DISPLAYNAME: flatbuffers::VOffsetT = 10;
  pub const VT_PARENTID: flatbuffers::VOffsetT = 12;
  pub const VT_COLOR: flatbuffers::VOffsetT = 14;
  pub const VT_RADIUS: flatbuffers::VOffsetT = 16;
  pub const VT_COLLAPSED: flatbuffers::VOffsetT = 18;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    GraphCombo { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args GraphComboArgs<'args>
  ) -> flatbuffers::WIPOffset<GraphCombo<'bldr>> {
    let mut builder = GraphComboBuilder::new(_fbb);
    builder.add_radius(args.radius);
    if let Some(x) = args.color { builder.add_color(x); }
    if let Some(x) = args.parentId { builder.add_parentId(x); }
    if let Some(x) = args.displayName { builder.add_displayName(x); }
    if let Some(x) = args.name { builder.add_name(x); }
    if let Some(x) = args.id { builder.add_id(x); }
    builder.add_collapsed(args.collapsed);
    builder.add_type_(args.type_);
    builder.finish()
  }


  #[inline]
  pub fn id(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(GraphCombo::VT_ID, None)}
  }
  #[inline]
  pub fn type_(&self) -> ItemType {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<ItemType>(GraphCombo::VT_TYPE_, Some(ItemType::Package)).unwrap()}
  }
  #[inline]
  pub fn name(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(GraphCombo::VT_NAME, None)}
  }
  #[inline]
  pub fn displayName(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(GraphCombo::VT_DISPLAYNAME, None)}
  }
  #[inline]
  pub fn parentId(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(GraphCombo::VT_PARENTID, None)}
  }
  #[inline]
  pub fn color(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(GraphCombo::VT_COLOR, None)}
  }
  #[inline]
  pub fn radius(&self) -> f32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f32>(GraphCombo::VT_RADIUS, Some(0.0)).unwrap()}
  }
  #[inline]
  pub fn collapsed(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(GraphCombo::VT_COLLAPSED, Some(false)).unwrap()}
  }
}

impl flatbuffers::Verifiable for GraphCombo<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("id", Self::VT_ID, false)?
     .visit_field::<ItemType>("type_", Self::VT_TYPE_, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("name", Self::VT_NAME, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("displayName", Self::VT_DISPLAYNAME, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("parentId", Self::VT_PARENTID, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("color", Self::VT_COLOR, false)?
     .visit_field::<f32>("radius", Self::VT_RADIUS, false)?
     .visit_field::<bool>("collapsed", Self::VT_COLLAPSED, false)?
     .finish();
    Ok(())
  }
}
pub struct GraphComboArgs<'a> {
    pub id: Option<flatbuffers::WIPOffset<&'a str>>,
    pub type_: ItemType,
    pub name: Option<flatbuffers::WIPOffset<&'a str>>,
    pub displayName: Option<flatbuffers::WIPOffset<&'a str>>,
    pub parentId: Option<flatbuffers::WIPOffset<&'a str>>,
    pub color: Option<flatbuffers::WIPOffset<&'a str>>,
    pub radius: f32,
    pub collapsed: bool,
}
impl<'a> Default for GraphComboArgs<'a> {
  #[inline]
  fn default() -> Self {
    GraphComboArgs {
      id: None,
      type_: ItemType::Package,
      name: None,
      displayName: None,
      parentId: None,
      color: None,
      radius: 0.0,
      collapsed: false,
    }
  }
}

pub struct GraphComboBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> GraphComboBuilder<'a, 'b> {
  #[inline]
  pub fn add_id(&mut self, id: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(GraphCombo::VT_ID, id);
  }
  #[inline]
  pub fn add_type_(&mut self, type_: ItemType) {
    self.fbb_.push_slot::<ItemType>(GraphCombo::VT_TYPE_, type_, ItemType::Package);
  }
  #[inline]
  pub fn add_name(&mut self, name: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(GraphCombo::VT_NAME, name);
  }
  #[inline]
  pub fn add_displayName(&mut self, displayName: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(GraphCombo::VT_DISPLAYNAME, displayName);
  }
  #[inline]
  pub fn add_parentId(&mut self, parentId: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(GraphCombo::VT_PARENTID, parentId);
  }
  #[inline]
  pub fn add_color(&mut self, color: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(GraphCombo::VT_COLOR, color);
  }
  #[inline]
  pub fn add_radius(&mut self, radius: f32) {
    self.fbb_.push_slot::<f32>(GraphCombo::VT_RADIUS, radius, 0.0);
  }
  #[inline]
  pub fn add_collapsed(&mut self, collapsed: bool) {
    self.fbb_.push_slot::<bool>(GraphCombo::VT_COLLAPSED, collapsed, false);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> GraphComboBuilder<'a, 'b> {
    let start = _fbb.start_table();
    GraphComboBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<GraphCombo<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for GraphCombo<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("GraphCombo");
      ds.field("id", &self.id());
      ds.field("type_", &self.type_());
      ds.field("name", &self.name());
      ds.field("displayName", &self.displayName());
      ds.field("parentId", &self.parentId());
      ds.field("color", &self.color());
      ds.field("radius", &self.radius());
      ds.field("collapsed", &self.collapsed());
      ds.finish()
  }
}
pub enum GraphEdgeOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct GraphEdge<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for GraphEdge<'a> {
  type Inner = GraphEdge<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> GraphEdge<'a> {
  pub const VT_ID: flatbuffers::VOffsetT = 4;
  pub const VT_SOURCE: flatbuffers::VOffsetT = 6;
  pub const VT_TARGET: flatbuffers::VOffsetT = 8;
  pub const VT_NAME: flatbuffers::VOffsetT = 10;
  pub const VT_KIND: flatbuffers::VOffsetT = 12;
  pub const VT_CATEGORY: flatbuffers::VOffsetT = 14;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    GraphEdge { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args GraphEdgeArgs<'args>
  ) -> flatbuffers::WIPOffset<GraphEdge<'bldr>> {
    let mut builder = GraphEdgeBuilder::new(_fbb);
    if let Some(x) = args.category { builder.add_category(x); }
    if let Some(x) = args.kind { builder.add_kind(x); }
    if let Some(x) = args.name { builder.add_name(x); }
    if let Some(x) = args.target { builder.add_target(x); }
    if let Some(x) = args.source { builder.add_source(x); }
    if let Some(x) = args.id { builder.add_id(x); }
    builder.finish()
  }


  #[inline]
  pub fn id(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(GraphEdge::VT_ID, None)}
  }
  #[inline]
  pub fn source(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(GraphEdge::VT_SOURCE, None)}
  }
  #[inline]
  pub fn target(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(GraphEdge::VT_TARGET, None)}
  }
  #[inline]
  pub fn name(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(GraphEdge::VT_NAME, None)}
  }
  #[inline]
  pub fn kind(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(GraphEdge::VT_KIND, None)}
  }
  #[inline]
  pub fn category(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(GraphEdge::VT_CATEGORY, None)}
  }
}

impl flatbuffers::Verifiable for GraphEdge<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("id", Self::VT_ID, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("source", Self::VT_SOURCE, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("target", Self::VT_TARGET, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("name", Self::VT_NAME, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("kind", Self::VT_KIND, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("category", Self::VT_CATEGORY, false)?
     .finish();
    Ok(())
  }
}
pub struct GraphEdgeArgs<'a> {
    pub id: Option<flatbuffers::WIPOffset<&'a str>>,
    pub source: Option<flatbuffers::WIPOffset<&'a str>>,
    pub target: Option<flatbuffers::WIPOffset<&'a str>>,
    pub name: Option<flatbuffers::WIPOffset<&'a str>>,
    pub kind: Option<flatbuffers::WIPOffset<&'a str>>,
    pub category: Option<flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for GraphEdgeArgs<'a> {
  #[inline]
  fn default() -> Self {
    GraphEdgeArgs {
      id: None,
      source: None,
      target: None,
      name: None,
      kind: None,
      category: None,
    }
  }
}

pub struct GraphEdgeBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> GraphEdgeBuilder<'a, 'b> {
  #[inline]
  pub fn add_id(&mut self, id: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(GraphEdge::VT_ID, id);
  }
  #[inline]
  pub fn add_source(&mut self, source: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(GraphEdge::VT_SOURCE, source);
  }
  #[inline]
  pub fn add_target(&mut self, target: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(GraphEdge::VT_TARGET, target);
  }
  #[inline]
  pub fn add_name(&mut self, name: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(GraphEdge::VT_NAME, name);
  }
  #[inline]
  pub fn add_kind(&mut self, kind: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(GraphEdge::VT_KIND, kind);
  }
  #[inline]
  pub fn add_category(&mut self, category: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(GraphEdge::VT_CATEGORY, category);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> GraphEdgeBuilder<'a, 'b> {
    let start = _fbb.start_table();
    GraphEdgeBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<GraphEdge<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for GraphEdge<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("GraphEdge");
      ds.field("id", &self.id());
      ds.field("source", &self.source());
      ds.field("target", &self.target());
      ds.field("name", &self.name());
      ds.field("kind", &self.kind());
      ds.field("category", &self.category());
      ds.finish()
  }
}
pub enum GraphNodeDetailOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct GraphNodeDetail<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for GraphNodeDetail<'a> {
  type Inner = GraphNodeDetail<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> GraphNodeDetail<'a> {
  pub const VT_ID: flatbuffers::VOffsetT = 4;
  pub const VT_FILENAME: flatbuffers::VOffsetT = 6;
  pub const VT_PROJECTPATH: flatbuffers::VOffsetT = 8;
  pub const VT_LOC: flatbuffers::VOffsetT = 10;
  pub const VT_DATA_JSON: flatbuffers::VOffsetT = 12;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    GraphNodeDetail { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args GraphNodeDetailArgs<'args>
  ) -> flatbuffers::WIPOffset<GraphNodeDetail<'bldr>> {
    let mut builder = GraphNodeDetailBuilder::new(_fbb);
    if let Some(x) = args.data_json { builder.add_data_json(x); }
    if let Some(x) = args.loc { builder.add_loc(x); }
    if let Some(x) = args.projectPath { builder.add_projectPath(x); }
    if let Some(x) = args.fileName { builder.add_fileName(x); }
    if let Some(x) = args.id { builder.add_id(x); }
    builder.finish()
  }


  #[inline]
  pub fn id(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(GraphNodeDetail::VT_ID, None)}
  }
  #[inline]
  pub fn fileName(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(GraphNodeDetail::VT_FILENAME, None)}
  }
  #[inline]
  pub fn projectPath(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(GraphNodeDetail::VT_PROJECTPATH, None)}
  }
  #[inline]
  pub fn loc(&self) -> Option<Loc<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<Loc>>(GraphNodeDetail::VT_LOC, None)}
  }
  #[inline]
  pub fn data_json(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(GraphNodeDetail::VT_DATA_JSON, None)}
  }
}

impl flatbuffers::Verifiable for GraphNodeDetail<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("id", Self::VT_ID, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("fileName", Self::VT_FILENAME, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("projectPath", Self::VT_PROJECTPATH, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<Loc>>("loc", Self::VT_LOC, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("data_json", Self::VT_DATA_JSON, false)?
     .finish();
    Ok(())
  }
}
pub struct GraphNodeDetailArgs<'a> {
    pub id: Option<flatbuffers::WIPOffset<&'a str>>,
    pub fileName: Option<flatbuffers::WIPOffset<&'a str>>,
    pub projectPath: Option<flatbuffers::WIPOffset<&'a str>>,
    pub loc: Option<flatbuffers::WIPOffset<Loc<'a>>>,
    pub data_json: Option<flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for GraphNodeDetailArgs<'a> {
  #[inline]
  fn default() -> Self {
    GraphNodeDetailArgs {
      id: None,
      fileName: None,
      projectPath: None,
      loc: None,
      data_json: None,
    }
  }
}

pub struct GraphNodeDetailBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> GraphNodeDetailBuilder<'a, 'b> {
  #[inline]
  pub fn add_id(&mut self, id: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(GraphNodeDetail::VT_ID, id);
  }
  #[inline]
  pub fn add_fileName(&mut self, fileName: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(GraphNodeDetail::VT_FILENAME, fileName);
  }
  #[inline]
  pub fn add_projectPath(&mut self, projectPath: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(GraphNodeDetail::VT_PROJECTPATH, projectPath);
  }
  #[inline]
  pub fn add_loc(&mut self, loc: flatbuffers::WIPOffset<Loc<'b >>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<Loc>>(GraphNodeDetail::VT_LOC, loc);
  }
  #[inline]
  pub fn add_data_json(&mut self, data_json: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(GraphNodeDetail::VT_DATA_JSON, data_json);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> GraphNodeDetailBuilder<'a, 'b> {
    let start = _fbb.start_table();
    GraphNodeDetailBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<GraphNodeDetail<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for GraphNodeDetail<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("GraphNodeDetail");
      ds.field("id", &self.id());
      ds.field("fileName", &self.fileName());
      ds.field("projectPath", &self.projectPath());
      ds.field("loc", &self.loc());
      ds.field("data_json", &self.data_json());
      ds.finish()
  }
}
pub enum GraphViewOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct GraphView<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for GraphView<'a> {
  type Inner = GraphView<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> GraphView<'a> {
  pub const VT_NODES: flatbuffers::VOffsetT = 4;
  pub const VT_COMBOS: flatbuffers::VOffsetT = 6;
  pub const VT_EDGES: flatbuffers::VOffsetT = 8;
  pub const VT_DETAILS: flatbuffers::VOffsetT = 10;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    GraphView { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args GraphViewArgs<'args>
  ) -> flatbuffers::WIPOffset<GraphView<'bldr>> {
    let mut builder = GraphViewBuilder::new(_fbb);
    if let Some(x) = args.details { builder.add_details(x); }
    if let Some(x) = args.edges { builder.add_edges(x); }
    if let Some(x) = args.combos { builder.add_combos(x); }
    if let Some(x) = args.nodes { builder.add_nodes(x); }
    builder.finish()
  }


  #[inline]
  pub fn nodes(&self) -> Option<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<GraphNode<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<GraphNode>>>>(GraphView::VT_NODES, None)}
  }
  #[inline]
  pub fn combos(&self) -> Option<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<GraphCombo<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<GraphCombo>>>>(GraphView::VT_COMBOS, None)}
  }
  #[inline]
  pub fn edges(&self) -> Option<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<GraphEdge<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<GraphEdge>>>>(GraphView::VT_EDGES, None)}
  }
  #[inline]
  pub fn details(&self) -> Option<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<GraphNodeDetail<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<GraphNodeDetail>>>>(GraphView::VT_DETAILS, None)}
  }
}

impl flatbuffers::Verifiable for GraphView<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<GraphNode>>>>("nodes", Self::VT_NODES, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<GraphCombo>>>>("combos", Self::VT_COMBOS, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<GraphEdge>>>>("edges", Self::VT_EDGES, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<GraphNodeDetail>>>>("details", Self::VT_DETAILS, false)?
     .finish();
    Ok(())
  }
}
pub struct GraphViewArgs<'a> {
    pub nodes: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<GraphNode<'a>>>>>,
    pub combos: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<GraphCombo<'a>>>>>,
    pub edges: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<GraphEdge<'a>>>>>,
    pub details: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<GraphNodeDetail<'a>>>>>,
}
impl<'a> Default for GraphViewArgs<'a> {
  #[inline]
  fn default() -> Self {
    GraphViewArgs {
      nodes: None,
      combos: None,
      edges: None,
      details: None,
    }
  }
}

pub struct GraphViewBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> GraphViewBuilder<'a, 'b> {
  #[inline]
  pub fn add_nodes(&mut self, nodes: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<GraphNode<'b >>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(GraphView::VT_NODES, nodes);
  }
  #[inline]
  pub fn add_combos(&mut self, combos: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<GraphCombo<'b >>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(GraphView::VT_COMBOS, combos);
  }
  #[inline]
  pub fn add_edges(&mut self, edges: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<GraphEdge<'b >>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(GraphView::VT_EDGES, edges);
  }
  #[inline]
  pub fn add_details(&mut self, details: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<GraphNodeDetail<'b >>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(GraphView::VT_DETAILS, details);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> GraphViewBuilder<'a, 'b> {
    let start = _fbb.start_table();
    GraphViewBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<GraphView<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for GraphView<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("GraphView");
      ds.field("nodes", &self.nodes());
      ds.field("combos", &self.combos());
      ds.field("edges", &self.edges());
      ds.field("details", &self.details());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `GraphView`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_graph_view_unchecked`.
pub fn root_as_graph_view(buf: &[u8]) -> Result<GraphView, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root::<GraphView>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `GraphView` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_graph_view_unchecked`.
pub fn size_prefixed_root_as_graph_view(buf: &[u8]) -> Result<GraphView, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root::<GraphView>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `GraphView` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_graph_view_unchecked`.
pub fn root_as_graph_view_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<GraphView<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root_with_opts::<GraphView<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `GraphView` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_graph_view_unchecked`.
pub fn size_prefixed_root_as_graph_view_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<GraphView<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root_with_opts::<GraphView<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a GraphView and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `GraphView`.
pub unsafe fn root_as_graph_view_unchecked(buf: &[u8]) -> GraphView {
  flatbuffers::root_unchecked::<GraphView>(buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed GraphView and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `GraphView`.
pub unsafe fn size_prefixed_root_as_graph_view_unchecked(buf: &[u8]) -> GraphView {
  flatbuffers::size_prefixed_root_unchecked::<GraphView>(buf)
}
pub const GRAPH_VIEW_IDENTIFIER: &str = "NXGV";

#[inline]
pub fn graph_view_buffer_has_identifier(buf: &[u8]) -> bool {
  flatbuffers::buffer_has_identifier(buf, GRAPH_VIEW_IDENTIFIER, false)
}

#[inline]
pub fn graph_view_size_prefixed_buffer_has_identifier(buf: &[u8]) -> bool {
  flatbuffers::buffer_has_identifier(buf, GRAPH_VIEW_IDENTIFIER, true)
}

#[inline]
pub fn finish_graph_view_buffer<'a, 'b>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>,
    root: flatbuffers::WIPOffset<GraphView<'a>>) {
  fbb.finish(root, Some(GRAPH_VIEW_IDENTIFIER));
}

#[inline]
pub fn finish_size_prefixed_graph_view_buffer<'a, 'b>(fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>, root: flatbuffers::WIPOffset<GraphView<'a>>) {
  fbb.finish_size_prefixed(root, Some(GRAPH_VIEW_IDENTIFIER));
}
}  // pub mod GraphView
}  // pub mod Nexiq

